version: '2'
services:
  progress-appserver:
    image: registry.ddev.fr/devops/docker-progress:${PROGRESS_VERSION}
    environment:
      APPLIC: /deal
      DLC: /usr/dlc
      WRKDIR: /deal/travail
    volumes_from:
    - source
    ports:
    - 9191:9090/tcp
  apache:
    image: registry.ddev.fr/devops/docker-php:${PHP_VERSION}
    volumes_from:
    - source
    ports:
    - 81:80/tcp
  tomcat:
    image: registry.ddev.fr/devops/docker-tomcat:${TOMCAT_VERSION}
    volumes_from:
    - source
    - progress-appserver
    ports:
    - 8181:8080/tcp
  source:
    image: registry.ddev.fr/devops/docker-source:latest
    environment:
      CLIENT: ${CLIENT}
    labels:
      io.rancher.sidekicks: progress-appserver,tomcat,apache
