version: '2'
services:  
  traefik:
    environment:
      ENDPOINT: ${endpoint}
      ACCESS_KEY: ${access_key}
      SECRET_KEY: ${secret_key}
    ports:
    - "${admin_port}:8080"
    - "${http_port}:80"
    - "${https_port}:443"
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.pull_image: 'always'
    tty: true
    image: nouts/traefik
