.catalog:
  name: traefik
  version: v1.3.1
  description: |
    (Experimental) Traefik load balancer.
  minimum_rancher_version: v0.59.0
  maintainer: "Deal"
  uuid: traefik-2
  questions:
    - variable: "http_port"
      description: "Traefik http public port to listen."
      label: "Http port:"
      required: true
      default: 80
      type: "int"
    - variable: "https_port"
      description: "Traefik https public port to listen."
      label: "Https port:"
      required: true
      default: 443
      type: "int"
    - variable: "admin_port"
      description: "Traefik admin public port to listen."
      label: "Admin port:"
      required: true
      default: 8181
      type: "int"
    - variable: endpoint
      description: "Endpoint décrit dans la section API (utilisateur ou environment)"
      label: "Endpoint Rancher"
      required: true
      default: "http://192.1.90.167:8080/v1/projects/1a7"
      type: string
    - variable: access_key
      description: ""
      label: "Clé d'accès"
      required: true
#      default: "XXXXXXXXXXXXXXXXXXXX"
      default: "D932895642C040BAD079"
      type: string
    - variable: secret_key
      description: ""
      label: "Clé secrète"
      required: true
#      default: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      default: "6GMmQUWLiswdNc4rgfdUg6ay1QmS88WYhyYt6fzt"
      type: string
    - variable: domain
      description: "doit être unique pour cet environnement Rancher"
      label: "Nom de domaine"
      required: true
      default: "docker.deal"
      type: string
traefik:
  start_on_create: true
  scale: 1
  health_check:
    port: 8080
    interval: 5000
    unhealthy_threshold: 3
    request_line: 'GET /dashboard/#/ HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 5000
