version: '2'
services:
  progress-appserver:
    image: registry.ddev.fr/devops/docker-progress:latest
    environment:
      APPLIC: /deal
      DLC: /usr/dlc
      WRKDIR: /deal/travail
      VIRTUAL_HOST: ${VHOST_PROGRESS}.master.local
    volumes:
    - deal:/deal
    - dlc:/usr/dlc
    ports:
    - 9090/tcp
  apache:
    image: registry.ddev.fr/devops/docker-php:5.3-apache
    environment:
      VIRTUAL_HOST: ${VHOST_APACHE}.master.local
    volumes:
    - deal:/deal
    ports:
    - 80/tcp
  tomcat:
    image: registry.ddev.fr/devops/docker-tomcat:8.5-jre8
    environment:
      VIRTUAL_HOST: ${VHOST_TOMCAT}.master.local
    volumes:
    - deal:/deal
    - dlc:/usr/dlc
    ports:
    - 8080/tcp
  source:
    image: registry.ddev.fr/devops/docker-source:latest
    volumes:
      - deal:/deal
    environment:
      CLIENT: 706
volumes:
  deal: {}
  dlc: {}