version: '2'
services:
  progress-appserver:
    image: registry.ddev.fr/devops/docker-progress:latest
    environment:
      APPLIC: /deal
      DLC: /usr/dlc
      WRKDIR: /deal/travail
    volumes:
    - deal:/deal
    - dlc:/usr/dlc
    labels:
      traefik.enable: "enable"
      traefik.domain: "$VHOST_PROGRESS"
      traefik.port: "9090"
      io.rancher.container.pull_image: 'true'
  apache:
    image: registry.ddev.fr/devops/docker-php:5.3-apache
    volumes:
    - deal:/deal
    labels:
      traefik.enable: "enable"
      traefik.domain: "$VHOST_APACHE"
      traefik.port: "80"
      io.rancher.container.pull_image: 'true'
  tomcat:
    image: registry.ddev.fr/devops/docker-tomcat:8.5-jre8
    volumes:
    - deal:/deal
    - dlc:/usr/dlc
    labels:
      traefik.enable: "enable"
      traefik.domain: "$VHOST_TOMCAT"
      traefik.port: "8080"
      io.rancher.container.pull_image: 'true'
  source:
    image: registry.ddev.fr/devops/docker-source:latest
    tty: true
    volumes:
      - deal:/deal
    environment:
      CLIENT: 706
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.pull_image: 'true'
volumes:
  deal: {}
  dlc: {}