.catalog:
  name: "ERP"
  version: "7.4"
  description: "blabla"
  uuid: erp-1
  minimum_rancher_version: v1.6.2
  questions:
    - variable: CLIENT
      description: "Selectionnez le numéro client pour configurer les sources"
      label: "Numéro de client"
      required: true
      default: 706
      type: enum
      options:
       - 086
       - 101
       - 169
       - 178
       - 188
       - 190
       - 196
       - 230
       - 238
       - 254
       - 273
       - 308
       - 309
       - 311
       - 325
       - 333
       - 334
       - 345
       - 352
       - 360
       - 361
       - 387
       - 389
       - 392
       - 395
       - 396
       - 401
       - 405
       - 415
       - 429
       - 435
       - 440
       - 443
       - 444
       - 445
       - 460
       - 462
       - 466
       - 470
       - 477
       - 479
       - 482
       - 485
       - 489
       - 500
       - 502
       - 504
       - 505
       - 509
       - 510
       - 513
       - 521
       - 523
       - 524
       - 525
       - 529
       - 535
       - 540
       - 543
       - 544
       - 556
       - 560
       - 567
       - 568
       - 588
       - 590
       - 591
       - 599
       - 600
       - 603
       - 606
       - 618
       - 620
       - 622
       - 625
       - 627
       - 628
       - 635
       - 638
       - 642
       - 646
       - 649
       - 653
       - 657
       - 659
       - 660
       - 667
       - 670
       - 671
       - 672
       - 676
       - 677
       - 678
       - 686
       - 687
       - 694
       - 696
       - 699
       - 701
       - 702
       - 703
       - 704
       - 705
       - 706
       - 709
       - 710
       - 732
       - 733
       - 734
       - 736
       - 738
       - 875
       - 990
       - 998
       - 999 
    - variable: PHP_VERSION
      description: "Selectionnez 5.3 si ERP version<=6. Selectionnez 7 si ERP version>=7"
      label: "Version de PHP"
      required: true
      default: 5.3-apache
      type: enum
      options:
       - 5.3-apache
       - 7-apache
progress:
  scale: 1
  start_on_create: true
  health_check:
    port: 9090
    #en milliseconde, verifie toutes les 2secondes
    interval: 2000
    #première vérification au bout de 3min30s
    initializing_timeout: 210000
    #marqué comme 'unhealthy' après 3tentatives
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    request_line: GET "/" "HTTP/1.0"
    #marqué comme 'healthy' après 2 réponses
    healthy_threshold: 2
apache:
  scale: 1
  start_on_create: true
  health_check:
    port: 80
    interval: 2000
    initializing_timeout: 180000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    request_line: GET "/" "HTTP/1.0"
    healthy_threshold: 2
tomcat:
  scale: 1
  start_on_create: true
  health_check:
    port: 8080
    interval: 2000
    initializing_timeout: 180000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    request_line: GET "/" "HTTP/1.0"
    healthy_threshold: 2
source:
  scale: 1
  start_on_create: true

