version: '2'
services:
  nginx:
    image: registry.ddev.fr/guillaume_v/rancher-templates:${VERSION}
    labels:
      traefik.enable: 'true'
      traefik.domain: "$VHOST"
      traefik.port: "8181"
      io.rancher.container.pull_image: 'true'
