.catalog:
  name: "NGINX"
  version: "1"
  description: blabla
  uuid: deal-0
  minimum_rancher_version: v1.6.2
  questions:
    - variable: VERSION
      description: ""
      label: "Version nginx"
      required: true
      default: v1
      type: enum
      options:
       - v1
       - v2
    - variable: VHOST
      description: "domaine pour accéder"
      label: "domaine"
      required: true
      default: master.local
      type: string
nginx:
  scale: 1
  start_on_create: true
  health_check:
    port: 80
    #en milliseconde, verifie toutes les 2secondes
    interval: 2000
    #première vérification au bout de 3min30s
    initializing_timeout: 60000
    #marqué comme 'unhealthy' après 3tentatives
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    request_line: GET "/" "HTTP/1.0"
    #marqué comme 'healthy' après 2 réponses
    healthy_threshold: 2
